#!/usr/bin/env bash
#Bash ssh script that configures a new Ubuntu machine to respect above requirements

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw -y allow 'Nginx HTTP'
sudo -i
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart
