#!/usr/bin/env bash
#Bash ssh script that configures a new Ubuntu machine to respect above requirements

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw -y allow 'Nginx HTTP'
sudo -i
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}/" /etc/nginx/sites-available/default
systemctl restart nginx
