#!/usr/bin/env bash
#Bash ssh script that configures a new Ubuntu machine to respect above requirements

sudo apt-get -y install nginx
sudo service nginx start
sed -i "s/server_name _;/server_name _;\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}/" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee  /var/www/html/custom_404.html
sudo service nginx start
