#!/usr/bin/env bash
# Write a Bash script that generates a MySQL dump and creates a compressed
mysqldump -u root -p --all-databases > backup.sql
now=$(date +"%d-%m-%Y")
tar -cvzf "$now.tar.gz" backup.sql
