#!/usr/bin/env bash
# "Holberton School" 10 times, with "Hi" preceding the 10th time

counter=1
while [ $counter -le 10 ]
do
    if [ $counter -eq 10 ]
    then
	echo "Hi"
    fi
    echo "Holberton School"
    ((counter++))
done
