#!/usr/bin/env bash
#  number 1-20 with bad luck statements for 4, 9, and 17

c=1
while [ $counter -le 20 ]
do
    echo $c
    case $c in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((c+1))
done