#!/usr/bin/env bash
#  number 1-20 with bad luck statements for 4, 9, and 17

counter=1
while [ $counter -le 20 ]
do
   echo $counter
   case $counter in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
   counter=$((counter+1))
done
