#!/usr/bin/env bash
# displays time for 12 hours and 59 minutes

hours=0
while [ $hours -le 12 ]
do
    echo "Hour: $hours"
    minutes=1
    while [ $minutes -le 59 ]
    do
	echo $minutes
	minutes=$((minutes+1))
    done
    minutes=$((hours+1))
done
