#!/usr/bin/env bash
# Write a Bash script that configures the container to fit the above requirements.
pkill -f apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 etc/nginx/nginx.conf
chmod 775 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start